### ISSUE TITLE
ConfigMap Update: PostHog API Host

### ISSUE THREAD

**Issue by joepavitt** [flowforge/helm#106]
### Description

As per https://github.com/flowforge/flowforge/pull/1649 we need to include a new option:

```
telemetry:
  enabled: true
  frontend:
    posthog:
      apihost: <apihost>
      apikey: <apikey>
      capture_pageview: false
```
