### ISSUE TITLE
helm upgade "does not appear to be a gzipped archive" typo in index file

### ISSUE THREAD

**Issue by flecoufle** [flowforge/helm#87]
### Current Behavior

```
apiVersion: v1
entries:
  flowforge:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2022-12-22T13:23:21.457462236Z"
    dependencies:
    - condition: forge.localPostgresql
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.14.0
    description: FlowForge
    digest: afd686492fbb152b49de6ae5c27f680156bdf4d12ebb73b47bb945bd122b002c
    home: https://flowforge.com
    icon: https://flowforge.com/apple-touch-icon.png
    keywords:
    - flowforge
    - node-red
    maintainers:
    - name: FlowForge Inc
      url: https://flowforge.com
    name: flowforge
    type: application
    urls:
    - https://flowforge.gibhub.io/helm/flowforge-1.2.0.tgz
```
gibhub -> github

### Steps To Reproduce

`helm upgrade --atomic --install flowforge flowforge/flowforge -f customization.yml
`
`Error: file '/xxxxxx/.cache/helm/repository/flowforge-1.2.0.tgz' does not appear to be a gzipped archive; got 'text/html; charset=utf-8'
`

### Environment

- FlowForge version: 1.2.0
- Node.js version: NR
- npm version: NR
- Platform/OS: x86_64
- Browser: NR
